### ISSUE TITLE
Japan Source

### ISSUE THREAD

**Issue by admiralkikan** [jonaaa20/itunes-web-sources#5]
Whenever I try to use the Japan source I get a 400 error.  Not entirely sure why that particular one has an issue but it does. I've tried it with 2 different isps and got the same result.

Also, it would be cool if it would be possible to create a source file from Lantis.jp website. I couldn't find what I needed to locate to create one. But maybe you can.

**Comment by jonaaa20** [comment]
Hello, could you try the latest 0.3 version and see if the Japan Source works?

**Comment by UserForTheOnlyTopic** [comment]
@jonaaa20 , sorry for offtop (i will edit-remove this message after your answer). Please check your e-mail and reply me or please upload those sources on some fileshare and give me a link here

**Comment by jonaaa20** [comment]
@userfortheonlytopic no, i read you email but i dont have the source, besides, the dev doesnt want to work on it anymore, that's why i deleted it.

**Comment by UserForTheOnlyTopic** [comment]
@jonaaa20 , it's clear. Just the scripts for that resource have been abandoned and i'm not interested in the existing app, so want to take a look at those files.

**Comment by UserForTheOnlyTopic** [comment]
@jonaaa20 i have those 2 scripts too, but maybe not the latest versions, i don't know, but they aren't working since like the beginning of this spring, but it seems that developers've changed something on client side to stop scripts when other mechanisms which use the same principles work, i.e. it seems it's easier to try to fix the plugin than scripts since their changes have been directed directly against scripts.
